CREATE USER IF NOT EXISTS admin IDENTIFIED BY 'pass';

DROP DATABASE IF EXISTS airbnb;
CREATE DATABASE airbnb DEFAULT CHARACTER SET utf8;

USE airbnb;

GRANT ALL ON airbnb.* TO 'admin'@'%';

FLUSH PRIVILEGES;